# Generated by Django 5.0.3 on 2024-04-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='starts',
            new_name='stars',
        ),
    ]
